### PR TITLE
Add type hinting

### PR DESCRIPTION
**Pull request by devRMA**
# Objective

My objective was to be able to run [mypy](https://github.com/python/mypy) in strict mode (``mypy --pretty --strict .``) without it reporting any errors.

I managed to reduce the vast majority of typing errors, only in the decorator [profile](https://github.com/jonghwanhyeon/python-stopwatch/blob/ca768783e9817c6ab1de1e71a74ad572963b24da/stopwatch/contextmanagers/profile.py#L32) that I couldn't do the typing.

I left a TODO in the decorator that I couldn't type, could you try to finish typing it?

I found this question on stackoverflow, but I still couldn't do the static typing, maybe this can help you.
https://stackoverflow.com/questions/47060133/python-3-type-hinting-for-decorator#answer-47060298

## These were the changes I made

- Fixed [W292](https://www.flake8rules.com/rules/W292.html)
- Added typing for the NamedTuple [Caller](https://github.com/jonghwanhyeon/python-stopwatch/blob/ca768783e9817c6ab1de1e71a74ad572963b24da/stopwatch/contextmanagers/__init__.py#L4)
- Added static typing for class attributes
- Added return type annotation on all functions/methods
- Added type hints in all parameters
- Added nanosecond and microsecond to to [format_elapsed_time](https://github.com/jonghwanhyeon/python-stopwatch/blob/main/stopwatch/contextmanagers/__init__.py#L12) function
- Added ``__str__`` and ``__repr__`` methods to [Stopwatch](https://github.com/jonghwanhyeon/python-stopwatch/blob/ca768783e9817c6ab1de1e71a74ad572963b24da/stopwatch/stopwatch.py#L33) to get elapsed time easier. Example:

```python
from stopwatch import Stopwatch

with Stopwatch() as stopwatch:
    ...
print(f'Elapsed time: {stopwatch}')  # Elapsed time: 1900.00ns
```

### CODE REVIEW

**Comment by devRMA** [comment]
I did my best, but I couldn't add the typing hinting to the decorator profile 😞 
Hope you can do it

**Comment by devRMA** [comment]
I found this solution, however it is only available for python 3.10
https://www.python.org/dev/peps/pep-0612/

**Comment by devRMA** [comment]
I managed to get this code
```python
from typing import Any, Callable, TypeVar

RT = TypeVar('RT')  # return type

def profile(**kwargs: Any) -> Callable[[Callable[..., RT]], Callable[..., RT]]:
    caller = inspect_caller()

    def decorator(func: Callable[..., RT]) -> Callable[..., RT]:
        name: str = kwargs.get('name', func.__name__)
        report_every: int = kwargs.get('report_every', 1)
        should_report = report_every is not None

        statistics = Statistics()
        atexit.register(print_report, caller, name, statistics)

        @functools.wraps(func)
        def wrapper(*args: object, **kwargs: object) -> RT:
            with Stopwatch() as stopwatch:
                result = func(*args, **kwargs)

            statistics.add(stopwatch.elapsed)
            if should_report and (len(statistics) % report_every) == 0:
                print_report(caller, name, statistics)

            return result

        return wrapper

    return decorator
```
however, will always need to use the decorator like this
```python
profile()
def foo: ...
```
will lose support for using without parentheses, like this
```python
@profile
def foo: ...
```
If you allow, I'll commit this change.

**Comment by jonghwanhyeon** [comment]
Sorry for checking late 😥. It was a holiday period in the area where I live. Except for `@profile()` thing, I would like to merge your pull request. If you don't mind, please open this pull request again.

**Pull request closed without merging**
